services:
  app:
    build: .
    container_name: simple-python-server
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 80:8000
    volumes:
      - .:/app
